import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import './globals.css';
import Footer from '@/components/common/Footer';
import NavHeader from '@/components/common/NavHeader';
import { PageProvider } from '@/contexts/PageContext';

export const metadata: Metadata = {
  title: 'Rydepro',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' dir='ltr'>
      <body className={` antialiased`}>
        <PageProvider>
          <NavHeader />
          {children}
          <Footer />
        </PageProvider>
      </body>
    </html>
  );
}
