export const ServiceAreas: {
  continent: string;
  code: string;

  regions: {
    region: string;
    code: string;
    provinces: { name: string; code: string }[];
  }[];
}[] = [
  {
    continent: 'South America',
    code: '',
    regions: [
      {
        region: 'Andean States',
        code: '',
        provinces: [
          { name: 'Bolivia BO', code: 'BO' },
          { name: 'Chile CL', code: 'CL' },
          { name: 'Colombia CO', code: 'CO' },
          { name: 'Ecuador EC', code: 'EC' },
          { name: 'Peru PE', code: 'PE' },
        ],
      },
      {
        region: 'Southern Cone',
        code: '',
        provinces: [
          { name: 'Argentina AR', code: 'AR' },
          { name: 'Chile CL', code: 'CL' },
          { name: 'Paraguay PY', code: 'PY' },
          { name: 'Uruguay UY', code: 'UY' },
        ],
      },
      {
        region: 'Northern South America',
        code: '',
        provinces: [
          { name: 'Brazil BR', code: 'BR' },
          { name: 'Guyana GY', code: 'GY' },
          { name: 'Suriname SR', code: 'SR' },
        ],
      },
      {
        region: 'Caribbean South America',
        code: '',
        provinces: [
          { name: 'Colombia CO', code: 'CO' },
          { name: 'Venezuela VE', code: 'VE' },
        ],
      },
      {
        region: 'Territories',
        code: '',
        provinces: [
          { name: 'Falkland Islands FK', code: 'FK' },
          { name: 'French Guiana GF', code: 'GF' },
          { name: 'South Georgia GS', code: 'GS' },
          { name: 'South Sandwich Islands S', code: 'SS' },
        ],
      },
    ],
  },
  {
    continent: 'CENTRAL AMERICA',
    code: '',
    regions: [
      {
        region: 'Belize BZ',
        code: 'BZ',
        provinces: [
          { name: 'Belize District', code: '' },
          { name: 'Stann Creek District SC', code: '' },
          { name: 'Corozal District CZL', code: '' },
          { name: 'Toledo District TOL', code: '' },

          { name: 'Orange Walk District OW', code: '' },
          { name: 'Cayo District CY', code: '' },
        ],
      },
      {
        region: 'Costa Rica CR',
        code: 'CR',
        provinces: [
          { name: 'Guanacaste Province G', code: '' },
          { name: 'Puntarenas Province P', code: '' },
          { name: 'Provincia de Cartago', code: '' },
          { name: 'Heredia', code: '' },
          { name: 'Limón', code: '' },

          { name: 'San José ', code: '' },
          { name: 'Alajuela', code: '' },
        ],
      },
      {
        region: 'El Salvador SV',
        code: 'SV',
        provinces: [
          { name: 'San Vicente Department SV', code: '' },
          { name: 'Santa Ana Department SA', code: '' },
          { name: 'Usulután Department US', code: '' },
          { name: 'Morazán Department MO', code: '' },
          { name: 'Chalatenango Department CH', code: '' },
          { name: 'Cabañas Department CA', code: '' },
          { name: 'San Salvador Department SS', code: '' },
          { name: 'La Libertad Department LI', code: '' },
          { name: 'San Miguel Department SM', code: '' },
          { name: 'La Paz Department PA', code: '' },
          { name: 'Cuscatlán Department CU', code: '' },
          { name: 'La Unión Department UN', code: '' },
          { name: 'Ahuachapán Department AH', code: '' },
          { name: 'Sonsonate Department SO', code: '' },
        ],
      },
      {
        region: 'Guatemala GT',
        code: 'GT',
        provinces: [
          { name: 'Quiché 14', code: '' },
          { name: 'Jalapa 21', code: '' },
          { name: 'Izabal 18', code: '' },
          { name: 'Suchitepéquez 10', code: '' },
          { name: 'Zacapa 22', code: '' },
          { name: 'San Marcos 15', code: '' },
          { name: 'Retalhuleu 16', code: '' },
          { name: 'Sololá 07', code: '' },
          { name: 'El Progreso 02', code: '' },
          { name: 'Totonicapán 08', code: '' },
          { name: 'Retalhuleu 11', code: '' },
          { name: 'Santa Rosa 06', code: '' },
          { name: 'Chiquimula 20', code: '' },
          { name: 'San Marcos 15', code: '' },
          { name: 'Quetzaltenango 09', code: '' },
          { name: 'Petén 17', code: '' },
          { name: 'Huehuetenango 13', code: '' },
          { name: 'Alta Verapaz 16', code: '' },
          { name: 'Guatemala 01', code: '' },
          { name: 'Jutiapa 22', code: '' },
          { name: 'Baja Verapaz 15', code: '' },
          { name: 'Chimaltenango 04', code: '' },
          { name: 'Sacatepéquez 03', code: '' },
          { name: 'Escuintla 05', code: '' },
          { name: 'Zacapa 19', code: '' },
        ],
      },
      {
        region: 'Honduras HN',
        code: 'HN',
        provinces: [
          { name: 'Choluteca Department CH', code: '' },
          { name: 'Comayagua Department CM', code: '' },
          { name: 'El Paraíso Department EP', code: '' },
          { name: 'Intibucá Department IN', code: '' },
          { name: 'Bay Islands Department IB', code: '' },
          { name: 'Cortés Department CR', code: '' },
          { name: 'Atlántida Department AT', code: '' },
          { name: 'Gracias a Dios Department GD', code: '' },
          { name: 'Copán Department CP', code: '' },
          { name: 'Olancho Department OL', code: '' },
          { name: 'Colón Department CL', code: '' },
          { name: 'Francisco Morazán Department FM', code: '' },
          { name: 'Santa Bárbara Department SB', code: '' },
          { name: 'Lempira Department LE', code: '' },
          { name: 'Ocotepeque Department OC', code: '' },
          { name: 'Yoro Department YO', code: '' },
          { name: 'La Paz Department LP', code: '' },
        ],
      },
      {
        region: 'Nicaragua NI',
        code: 'NI',
        provinces: [
          { name: 'Chontales CO', code: '' },
          { name: 'Managua MN', code: '' },
          { name: 'Rivas RI', code: '' },
          { name: 'Granada GR', code: '' },
          { name: 'León LE', code: '' },
          { name: 'Estelí ES', code: '' },
          { name: 'Boaco BO', code: '' },
          { name: 'Matagalpa MT', code: '' },
          { name: 'Madriz MD', code: '' },
          { name: 'Río San Juan SJ', code: '' },
          { name: 'Carazo CA', code: '' },
          { name: 'North Caribbean Coast AN', code: '' },
          { name: 'South Caribbean Coast AS', code: '' },
          { name: 'Masaya MS', code: '' },
          { name: 'Chinandega CI', code: '' },
          { name: 'Jinotega JI', code: '' },
          { name: 'Nueva Segovia NS', code: '' },
        ],
      },
      {
        region: 'Panama PA',
        code: 'PA',
        provinces: [
          { name: 'Darién Province 5', code: '' },
          { name: 'Colón Province 3', code: '' },
          { name: 'Coclé Province 2', code: '' },
          { name: 'Guna Yala KY', code: '' },
          { name: 'Herrera Province 6', code: '' },
          { name: 'Los Santos Province 7', code: '' },
          { name: 'Ngöbe-Buglé Comarca NB', code: '' },
          { name: 'Veraguas Province 9', code: '' },
          { name: 'Bocas del Toro Province 1', code: '' },
          { name: 'Panamá Oeste Province 10', code: '' },
          { name: 'Panamá Province 8', code: '' },
          { name: 'Emberá-Wounaan Comarca EM', code: '' },
          { name: 'Chiriquí Province 4', code: '' },
        ],
      },
      {
        region: 'Caribbean',
        code: '',
        provinces: [
          { name: 'Anguilla AI', code: 'AI' },
          { name: 'Antigua and Barbuda AG', code: 'AG' },
          { name: 'Aruba AW', code: 'AW' },
          { name: 'The Bahamas BS', code: 'BS' },
          { name: 'Barbados BB', code: 'BB' },
          { name: 'Cayman Islands KY', code: 'KY' },
          { name: 'Cuba CU', code: 'CU' },
          { name: 'Dominica DM', code: 'DM' },
          { name: 'Dominican Republic DO', code: 'DO' },
          { name: 'Grenada GD', code: 'GD' },
          { name: 'Guadeloupe GP', code: 'GP' },
          { name: 'Haiti HT', code: 'HT' },
          { name: 'Jamaica JM', code: 'JM' },
          { name: 'Martinique MQ', code: 'MQ' },
          { name: 'Montserrat MS', code: 'MS' },
          { name: 'Bonaire, Sint Eustatius and Saba BQ', code: 'BQ' },
          { name: 'Puerto Rico PR', code: 'PR' },
          { name: 'Saint Kitts and Nevis KN', code: 'KN' },
          { name: 'Saint Lucia LC', code: 'LC' },
          { name: 'Saint Vincent and the Grenadines VC', code: 'VC' },
          { name: 'Saint-Barthelemy BL', code: 'BL' },
          { name: 'Saint-Martin (French part) MF', code: 'MF' },
          { name: 'Trinidad and Tobago TT', code: 'TT' },
          { name: 'Turks and Caicos Islands TC', code: 'TC' },
          { name: 'Virgin Islands (British) VG', code: 'VG' },
          { name: 'Virgin Islands (US) VI', code: 'VI' },
          { name: 'Curaçao CW', code: 'CW' },
          { name: 'Sint Maarten (Dutch part) SX', code: 'SX' },
        ],
      },
    ],
  },
  // {
  //   continent: 'South America',
  //   code: '',
  //   regions: [
  //     {
  //       region: 'Andean provinces',
  //       code: '',
  //       provinces: [
  //         { name: 'Bolivia', code: '' },
  //         { name: 'Ecuador', code: '' },
  //         { name: 'Peru', code: '' },
  //       ],
  //     },
  //     {
  //       region: 'Southern Cone',
  //       code: '',
  //       provinces: [
  //         { name: 'Argentina', code: '' },
  //         { name: 'Chile', code: '' },
  //         { name: 'Paraguay', code: '' },
  //         { name: 'Uruguay', code: '' },
  //       ],
  //     },
  //     {
  //       region: 'Northern South America',
  //       code: '',
  //       provinces: [
  //         { name: 'Colombia', code: '' },
  //         { name: 'Venezuela', code: '' },
  //         { name: 'Guyana', code: '' },
  //         { name: 'Suriname', code: '' },
  //       ],
  //     },
  //   ],
  // },
  {
    continent: 'Europe',
    code: '',
    regions: [
      {
        region: 'Northern Europe',
        code: '',
        provinces: [
          { name: 'Denmark DK', code: 'DK' },
          { name: 'Estonia EE', code: 'EE' },
          { name: 'Finland FI', code: 'FI' },
          { name: 'Iceland IS', code: 'IS' },
          { name: 'Ireland IE', code: 'IE' },
          { name: 'Latvia LV', code: 'LV' },
          { name: 'Lithuania LT', code: 'LT' },
          { name: 'Norway NO', code: 'NO' },
          { name: 'Sweden SE', code: 'SE' },
        ],
      },
      {
        region: 'Southern Europe',
        code: '',
        provinces: [
          { name: 'Albania AL', code: 'AL' },
          { name: 'Andorra AD', code: 'AD' },
          { name: 'Bosnia and Herzegovina BA', code: 'BA' },
          { name: 'Croatia HR', code: 'HR' },
          { name: 'Cyprus CY', code: 'CY' },
          { name: 'Gibraltar GI', code: 'GI' },
          { name: 'Greece GR', code: 'GR' },
          { name: 'Italy IT', code: 'IT' },
          { name: 'North Macedonia MK', code: 'MK' },
          { name: 'Malta MT', code: 'MT' },
          { name: 'Montenegro ME', code: 'ME' },
          { name: 'Portugal PT', code: 'PT' },
          { name: 'San Marino SM', code: 'SM' },
          { name: 'Serbia RS', code: 'RS' },
          { name: 'Slovenia SI', code: 'SI' },
          { name: 'Spain ES', code: 'ES' },
          { name: 'Vatican City State (Holy See) VA', code: 'VA' },
        ],
      },
      {
        region: 'Western Europe',
        code: '',
        provinces: [
          { name: 'Austria AT', code: 'AT' },
          { name: 'Belgium BE', code: 'BE' },
          { name: 'France FR', code: 'FR' },
          { name: 'Germany DE', code: 'DE' },
          { name: 'Liechtenstein LI', code: 'LI' },
          { name: 'Luxembourg LU', code: 'LU' },
          { name: 'Monaco MC', code: 'MC' },
          { name: 'Netherlands NL', code: 'NL' },
          { name: 'Switzerland CH', code: 'CH' },
        ],
      },

      {
        region: 'Eastern Europe',
        code: '',
        provinces: [
          { name: 'Belarus BY', code: 'BY' },
          { name: 'Bulgaria BG', code: 'BG' },
          { name: 'Czech Republic CZ', code: 'CZ' },
          { name: 'Hungary HU', code: 'HU' },
          { name: 'Moldova MD', code: 'MD' },
          { name: 'Poland PL', code: 'PL' },
          { name: 'Romania RO', code: 'RO' },
          { name: 'Russia RU', code: 'RU' },
          { name: 'Slovakia SK', code: 'SK' },
          { name: 'Ukraine UA', code: 'UA' },
          { name: 'Kosovo XK', code: 'XK' },
        ],
      },
      {
        region: 'Territories',
        code: '',
        provinces: [
          { name: 'Aland Islands AX', code: 'AX' },
          { name: 'Faroe Islands FO', code: 'FO' },
          { name: 'Guernsey and Alderney GG', code: 'GG' },
          { name: 'Svalbard and Jan Mayen Islands SJ', code: 'SJ' },
          { name: 'Isle of Man IM', code: 'IM' },
          { name: 'Jersey JE', code: 'JE' },
          { name: 'Svalbard and Jan Mayen Islands SJ', code: 'SJ' },
        ],
      },
    ],
  },
  {
    continent: 'Africa',
    code: '',
    regions: [
      {
        region: 'Northern Africa',
        code: '',
        provinces: [
          { name: 'Algeria DZ', code: 'DZ' },
          { name: 'Egypt EG', code: 'EG' },
          { name: 'Libya LY', code: 'LY' },
          { name: 'Morocco MA', code: 'MA' },
          { name: 'Sudan SD', code: 'SD' },
          { name: 'Tunisia TN', code: 'TN' },
          { name: 'Western Sahara EH', code: 'EH' },
        ],
      },
      {
        region: 'Western Africa',
        code: '',
        provinces: [
          { name: 'Benin BJ', code: 'BJ' },
          { name: 'Burkina Faso BF', code: 'BF' },
          { name: 'Cape Verde CV', code: 'CV' },
          { name: "Cote D'Ivoire (Ivory Coast) CI", code: 'CI' },
          { name: 'The Gambia GM', code: 'GM' },
          { name: 'Ghana GH', code: 'GH' },
          { name: 'Guinea GN', code: 'GN' },
          { name: 'Guinea-Bissau GW', code: 'GW' },
          { name: 'Liberia LR', code: 'LR' },
          { name: 'Mali ML', code: 'ML' },
          { name: 'Mauritania MR', code: 'MR' },
          { name: 'Niger NE', code: 'NE' },
          { name: 'Nigeria NG', code: 'NG' },
          { name: 'Senegal SN', code: 'SN' },
          { name: 'Sierra Leone SL', code: 'SL' },
          { name: 'Togo TG', code: 'TG' },
        ],
      },
      {
        region: 'Eastern Africa',
        code: '',
        provinces: [
          { name: 'Burundi BI', code: 'BI' },
          { name: 'Comoros KM', code: 'KM' },
          { name: 'Djibouti DJ', code: 'DJ' },
          { name: 'Eritrea ER', code: 'ER' },
          { name: 'Ethiopia ET', code: 'ET' },
          { name: 'Kenya KE', code: 'KE' },
          { name: 'Madagascar MG', code: 'MG' },
          { name: 'Malawi MW', code: 'MW' },
          { name: 'Mauritius MU', code: 'MU' },
          { name: 'Mozambique MZ', code: 'MZ' },
          { name: 'Rwanda RW', code: 'RW' },
          { name: 'Seychelles SC', code: 'SC' },
          { name: 'Somalia SO', code: 'SO' },
          { name: 'South Sudan SS', code: 'SS' },
          { name: 'Tanzania TZ', code: 'TZ' },
          { name: 'Uganda UG', code: 'UG' },
          { name: 'Zambia ZM', code: 'ZM' },
          { name: 'Zimbabwe ZW', code: 'ZW' },
        ],
      },
      {
        region: 'Southern Africa',
        code: '',
        provinces: [
          { name: 'Botswana', code: '' },
          { name: 'Eswatini', code: '' },
          { name: 'Lesotho', code: '' },
          { name: 'Namibia', code: '' },
          { name: 'South Africa', code: '' },
          { name: 'Zambia', code: '' },
          { name: 'Zimbabwe', code: '' },
        ],
      },
      {
        region: 'Central Africa',
        code: '',
        provinces: [
          { name: 'Angola', code: '' },
          { name: 'Cameroon', code: '' },
          { name: 'Central African Republic', code: '' },
          { name: 'Chad', code: '' },
          { name: 'Democratic Republic of the Congo', code: '' },
          { name: 'Republic of the Congo', code: '' },
          { name: 'Equatorial Guinea', code: '' },
          { name: 'Gabon', code: '' },
          { name: 'Sao Tome and Principe', code: '' },
        ],
      },
    ],
  },
  {
    continent: 'Asia',
    code: '',
    regions: [
      {
        region: 'Eastern Asia',
        code: '',
        provinces: [
          { name: 'China CN', code: 'CN' },
          { name: 'Hong Kong S.A.R. HK', code: 'HK' },
          { name: 'Japan JP', code: 'JP' },
          { name: 'North Korea KP', code: 'KP' },
          { name: 'South Korea KR', code: 'KR' },
          { name: 'Macau S.A.R. MO', code: 'MO' },
          { name: 'Mongolia MN', code: 'MN' },
          { name: 'Taiwan TW', code: 'TW' },
        ],
      },
      {
        region: 'Southeast Asia',
        code: '',
        provinces: [
          { name: 'Brunei BN', code: 'BN' },
          { name: 'Cambodia KH', code: 'KH' },
          { name: 'Timor-Leste TL', code: 'TL' },
          { name: 'Indonesia ID', code: 'ID' },
          { name: 'Laos LA', code: 'LA' },
          { name: 'Malaysia MY', code: 'MY' },
          { name: 'Myanmar MM', code: 'MM' },
          { name: 'Philippines PH', code: 'PH' },
          { name: 'Singapore SG', code: 'SG' },
          { name: 'Thailand TH', code: 'TH' },
          { name: 'Vietnam VN', code: 'VN' },
        ],
      },
      {
        region: 'South Asia',
        code: '',
        provinces: [
          { name: 'Afghanistan AF', code: 'AF' },
          { name: 'Bangladesh BD', code: 'BD' },
          { name: 'Bhutan BT', code: 'BT' },
          { name: 'India IN', code: 'IN' },
          { name: 'Iran IR', code: 'IR' },
          { name: 'Maldives MV', code: 'MV' },
          { name: 'Nepal NP', code: 'NP' },
          { name: 'Pakistan PK', code: 'PK' },
          { name: 'Sri Lanka LK', code: 'LK' },
        ],
      },
      {
        region: 'Central Asia',
        code: '',
        provinces: [
          { name: 'Kazakhstan KZ', code: '' },
          { name: 'Kyrgyzstan KG', code: 'KG' },
          { name: 'Tajikistan TJ', code: 'TJ' },
          { name: 'Turkmenistan TM', code: 'TM' },
          { name: 'Uzbekistan UZ', code: 'UZ' },
        ],
      },
      {
        region: 'Western Asia',
        code: '',
        provinces: [
          { name: 'Armenia AM', code: 'AM' },
          { name: 'Azerbaijan AZ', code: 'AZ' },
          { name: 'Bahrain BH', code: 'BH' },
          { name: 'Georgia GE', code: 'GE' },
          { name: 'Iraq IQ', code: 'IQ' },
          { name: 'Israel IL', code: 'IL' },
          { name: 'Jordan JO', code: 'JO' },
          { name: 'Kuwait KW', code: 'KW' },
          { name: 'Lebanon LB', code: 'LB' },
          { name: 'Oman OM', code: 'OM' },
          { name: 'Palestinian Territory Occupied PS', code: 'PS' },
          { name: 'Qatar QA', code: 'QA' },
          { name: 'Saudi Arabia SA', code: 'SA' },
          { name: 'Syria SY', code: 'SY' },
          { name: 'Turkey TR', code: 'TR' },
          { name: 'United Arab Emirates AE', code: 'AE' },
          { name: 'Yemen YE', code: 'YE' },
        ],
      },
    ],
  },
  {
    continent: 'Oceania',
    code: '',
    regions: [
      {
        region: 'Pacific Islands',
        code: '',
        provinces: [
          { name: 'Fiji', code: '' },
          { name: 'Papua New Guinea', code: '' },
          { name: 'Samoa', code: '' },
          { name: 'Solomon Islands', code: '' },
          { name: 'Tonga', code: '' },
          { name: 'Vanuatu', code: '' },
          { name: 'Kiribati', code: '' },
          { name: 'Tuvalu', code: '' },
          { name: 'Nauru', code: '' },
          { name: 'Palau', code: '' },
          { name: 'Micronesia', code: '' },
          { name: 'Marshall Islands', code: '' },
        ],
      },
      {
        region: 'Australia and New Zealand',
        code: '',
        provinces: [
          { name: 'Australia AU', code: 'AU' },
          { name: 'Christmas Island CX', code: 'CX' },
          { name: 'Cocos (Keeling) Islands CC', code: 'CC' },
          { name: 'New Zealand NZ', code: 'NZ' },
          { name: 'Norfolk Island NF', code: 'NF' },
        ],
      },
      {
        region: 'Melanesia',
        code: '',
        provinces: [
          { name: 'Papua New Guinea PG', code: 'PG' },
          { name: 'Fiji FJ', code: 'FJ' },
          { name: 'Solomon Islands SB', code: 'SB' },
          { name: 'Vanuatu VU', code: 'VU' },
          { name: 'New Caledonia NC', code: 'NC' },
        ],
      },
      {
        region: 'Micronesia',
        code: '',
        provinces: [
          { name: 'Federated States of Micronesia FM', code: 'FM' },
          { name: 'Marshall Islands MH', code: 'MH' },
          { name: 'Nauru NR', code: 'NR' },
          { name: 'Kiribati KI', code: 'KI' },
          { name: 'Palau PW', code: 'PW' },
          { name: 'Guam GU', code: 'GU' },
          { name: 'Northern Mariana Islands MP', code: 'MP' },
        ],
      },
      {
        region: 'Polynesia',
        code: '',
        provinces: [
          { name: 'American Samoa AS', code: 'AS' },
          { name: 'Cook Islands CK', code: 'CK' },
          { name: 'French Polynesia PF', code: 'PF' },
          { name: 'Niue NU', code: 'NU' },
          { name: 'Pitcairn Island PN', code: 'PN' },
          { name: 'Samoa WS', code: 'WS' },
          { name: 'Tokelau TK', code: 'TK' },
          { name: 'Tonga TO', code: 'TO' },
          { name: 'Tuvalu TV', code: 'TV' },
          { name: 'Wallis and Futuna Islands WF', code: 'WF' },
          { name: 'New Zealand NZ', code: 'NZ' },
          { name: 'Kiribati KI', code: 'KI' },
          { name: 'Hawaii HI', code: 'HI' },
        ],
      },
    ],
  },

  {
    continent: 'Antarctica',
    code: '',
    regions: [
      {
        region: 'Territories',
        code: '',
        provinces: [
          { name: 'Adélie Land (claimed by France) AQ', code: 'AQ' },
          {
            name: 'Argentine Antarctica (claimed by Argentina) AR',
            code: 'AR',
          },
          {
            name: 'Australian Antarctic Territory (claimed by Australia) AU',
            code: 'AU',
          },
          {
            name: 'British Antarctic Territory (claimed by the United Kingdom) GB',
            code: 'GB',
          },
          {
            name: 'Chilean Antarctic Territory (claimed by Chile) CL',
            code: 'CL',
          },
          { name: 'Peter I Island (claimed by Norway) NO', code: 'NO' },
          { name: 'Queen Maud Land (claimed by Norway) NO', code: 'NO' },
          { name: 'Ross Dependency (claimed by New Zealand) NZ', code: 'NZ' },
        ],
      },
    ],
  },
];

export const ServiceAreas1: {
  continent: string;
  code: string;
  states: {
    country: string;
    code: string;
    regions: {
      region: string;
      code: string;
      provinces: {
        name: string;
        code: string;
      }[];
    }[];
  }[];
}[] = [
  {
    continent: 'North America',
    code: '',
    states: [
      {
        country: 'United States US',
        code: 'US',
        regions: [
          {
            region: 'Southeast',
            code: '',
            provinces: [
              { name: 'Alabama', code: '' },
              { name: 'Arkansas', code: '' },
              { name: 'Florida', code: '' },
              { name: 'Georgia', code: '' },
              { name: 'Kentucky', code: '' },
              { name: 'Louisiana', code: '' },
              { name: 'Mississippi', code: '' },
              { name: 'North Carolina', code: '' },
              { name: 'South Carolina', code: '' },
              { name: 'Tennessee', code: '' },
            ],
          },
          {
            region: 'Midwest',
            code: '',
            provinces: [
              { name: 'Illinois', code: '' },
              { name: 'Indiana', code: '' },
              { name: 'Iowa', code: '' },
              { name: 'Michigan', code: '' },
              { name: 'Minnesota', code: '' },
              { name: 'Missouri', code: '' },
              { name: 'Ohio', code: '' },
              { name: 'Wisconsin', code: '' },
            ],
          },
          {
            region: 'Mid Atlantic',
            code: '',
            provinces: [
              { name: 'Delaware', code: '' },
              { name: 'District of Columbia', code: '' },
              { name: 'New Jersey', code: '' },
              { name: 'New York', code: '' },
              { name: 'Pennsylvania', code: '' },
              { name: 'Virginia', code: '' },
              { name: 'West Virginia', code: '' },
            ],
          },
          {
            region: 'Northeast',
            code: '',
            provinces: [
              { name: 'Connecticut', code: '' },
              { name: 'Maine', code: '' },
              { name: 'Massachusetts', code: '' },
              { name: 'New Hampshire', code: '' },
              { name: 'Rhode Island', code: '' },
              { name: 'Vermont', code: '' },
            ],
          },
          {
            region: 'Central',
            code: '',
            provinces: [
              { name: 'Colorado', code: '' },
              { name: 'Kansas', code: '' },
              { name: 'Montana', code: '' },
              { name: 'Nebraska', code: '' },
              { name: 'North Dakota', code: '' },
              { name: 'South Dakota', code: '' },
              { name: 'Wyoming', code: '' },
            ],
          },
          {
            region: 'Southwest',
            code: '',
            provinces: [
              { name: 'Arizona', code: '' },
              { name: 'New Mexico', code: '' },
              { name: 'Nevada', code: '' },
              { name: 'Utah', code: '' },
            ],
          },
          {
            region: 'West Coast',
            code: '',
            provinces: [
              { name: 'California', code: '' },
              { name: 'Oregon', code: '' },
              { name: 'Washington', code: '' },
            ],
          },
          {
            region: 'South',
            code: '',
            provinces: [
              { name: 'Texas', code: '' },
              { name: 'Oklahoma', code: '' },
            ],
          },
          {
            region: 'Northwest',
            code: '',
            provinces: [
              { name: 'Idaho', code: '' },
              { name: 'Montana', code: '' },
              { name: 'Washington', code: '' },
              { name: 'Wyoming', code: '' },
            ],
          },
        ],
      },
      {
        country: 'Canada CA',
        code: 'CA',
        regions: [
          {
            region: 'Pacific',
            code: '',
            provinces: [{ name: 'British Columbia', code: '' }],
          },
          {
            region: 'Prairies',
            code: '',
            provinces: [
              { name: 'Alberta', code: '' },
              { name: 'Saskatchewan', code: '' },
              { name: 'Manitoba', code: '' },
            ],
          },
          {
            region: 'Central Canada',
            code: '',
            provinces: [
              { name: 'Ontario', code: '' },
              { name: 'Quebec', code: '' },
            ],
          },
          {
            region: 'Atlantic Canada',
            code: '',
            provinces: [
              { name: 'New Brunswick', code: '' },
              { name: 'Newfoundland and Labrador', code: '' },
              { name: 'Nova Scotia', code: '' },
              { name: 'Prince Edward Island', code: '' },
            ],
          },
          {
            region: 'Canadian Territories',
            code: '',
            provinces: [
              { name: 'Yukon', code: '' },
              { name: 'Northwest Territories', code: '' },
              { name: 'Nunavut', code: '' },
            ],
          },
        ],
      },

      {
        country: 'Bermuda',
        code: 'BM',
        regions: [
          {
            region: 'Bermuda',
            code: '',
            provinces: [
              { name: 'Devonshire DEV', code: '' },
              { name: 'Hamilton HA', code: '' },
              { name: 'Paget PAG', code: '' },
              { name: 'Pembroke PEM', code: '' },
              { name: "Saint George's", code: '' },
              { name: 'Sandys SAN', code: '' },
              { name: "Smith's", code: '' },
              { name: 'Southampton SOU', code: '' },
              { name: 'Warwick WAR', code: '' },
            ],
          },
        ],
      },
      {
        country: 'Saint Pierre and Miquelon PM',
        code: 'PM',
        regions: [
          {
            region: '...',
            code: '',
            provinces: [{ name: '...', code: '' }],
          },
        ],
      },
      {
        country: 'Greenland',
        code: 'GL',
        regions: [
          {
            region: '...',
            code: '',
            provinces: [{ name: '...', code: '' }],
          },
        ],
      },
      {
        country: 'United States Minor Outlying Islands',
        code: 'UM',
        regions: [
          {
            region: 'United States Minor Outlying Islands',
            code: '',
            provinces: [
              { name: 'Baker Island', code: '' },
              { name: 'Howland Island', code: '' },
              { name: 'Jarvis Island', code: '' },
              { name: 'Johnston Atoll', code: '' },
              { name: 'Kingman Reef', code: '' },
              { name: 'Midway Islands', code: '' },
              { name: 'Navassa Island', code: '' },
              { name: 'Palmyra Atoll', code: '' },
              { name: 'Wake Island', code: '' },
            ],
          },
        ],
      },
      {
        country: 'Mexico',
        code: 'MX',
        regions: [
          {
            region: 'Northern Mexico',
            code: '',
            provinces: [
              { name: 'Baja California BCN', code: '' },
              { name: 'Baja California Sur BCS', code: '' },
              { name: 'Chihuahua CHH', code: '' },
              { name: 'Coahuila de Zaragoza COA', code: '' },
              { name: 'Durango DUR', code: '' },
              { name: 'Nuevo León NLE', code: '' },
              { name: 'Sinaloa SIN', code: '' },
              { name: 'Sonora SON', code: '' },
              { name: 'Tamaulipas TAM', code: '' },
              { name: 'Zacatecas ZAC', code: '' },
            ],
          },
          {
            region: 'Central Mexico',
            code: '',
            provinces: [
              { name: 'Aguascalientes AGU', code: '' },
              { name: 'Ciudad de Mexico', code: '' },
              { name: 'Estado de Mexico', code: '' },
              { name: 'Guanajuato GUA', code: '' },
              { name: 'Hidalgo HGO', code: '' },
              { name: 'Jalisco JAL', code: '' },
              { name: 'Morelos MOR', code: '' },
              { name: 'Puebla PUE', code: '' },
              { name: 'Querétaro QUE', code: '' },
              { name: 'San Luis Potosí SLP', code: '' },
              { name: 'Tlaxcala TLA', code: '' },
            ],
          },
          {
            region: 'Southern Mexico',
            code: '',
            provinces: [
              { name: 'Campeche CHP', code: '' },
              { name: 'Guerrero GRO', code: '' },
              { name: 'Michoacan de Ocampo MIC', code: '' },
              { name: 'Oaxaca OAX', code: '' },
              { name: 'Tabasco TAB', code: '' },
              { name: 'Veracruz de Ignacio de la VER', code: '' },
              { name: 'Llave VER', code: '' },
            ],
          },
          {
            region: 'Southeast and Yucatan Peninsula',
            code: '',
            provinces: [
              { name: 'Campeche CAM', code: '' },
              { name: 'Colima COL', code: '' },
              { name: 'Nayarit NAY', code: '' },
              { name: 'Quintana Roo ROO', code: '' },
              { name: 'Yucatán YUC', code: '' },
            ],
          },
        ],
      },
    ],
  },
];
